services:
  backend:
    build: ./backend
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - DSN=file:/app/data/chess_site.db?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)
    volumes:
      - ./data:/app/data  # persist SQLite db

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/cmd/web/localhost.crt:/etc/nginx/certs/localhost.crt
      - ./backend/cmd/web/localhost.key:/etc/nginx/certs/localhost.key
    depends_on:
      - backend
